### ISSUE TITLE
Threadsafe getters for global identifiers

### ISSUE THREAD

**Issue by hokb** [HDFGroup/HDF.PInvoke#97] opened 2016-10-15 13:30 UTC
According to https://github.com/HDFGroup/HDF.PInvoke/issues/96 the getters for global identifiers expose a race condition, hence are not threadsafe. These identifiers are used quite often all over the API. So, if possible, we do not want to use 'lock' here. This is even more true for a pot. future version of HDF5 which might allow true multithreading _efficiency_ (in contrast to todays thread safety 'only'). 

In order to make the caching of the global static variables threadsafe `System.Threading.Interlocked.Exchange` is more efficient than locking. It can be used to assign the retrieved value to the private attribute cache in all similar places (H5[E,P,T,..?]globals.cs). Based on todays implementation this is a bit trickier than it might seem at a first glance because we store the cached values as `Nullable<T>`. Atomic exchange via `System.Threading.Interlocked` works with common value types or reference types only. We could [make it work](http://stackoverflow.com/questions/5719770/interlocked-exchange-nullable-decimal) by some serious casting to `object` but I think it's not worth the additional complication. 

So I propose the following solution instead. It assumes that all global identifiers - once initialized - have some positive value. (@gheber is this fair to assume?). Also, it requires a modification of the generation of these getters. Here the example of `H5P_CLS_FILE_CREATE`: 

```
       // once per file: define the reserved value for initialization 
       private const hid_t HID_UNINITIALIZED = -1; 

        // the private cache is not a nullable anymore:
        static  hid_t H5P_CLS_FILE_CREATE_g = HID_UNINITIALIZED;

        public static hid_t FILE_CREATE 
        {
            get
            {
#if HDF5_VER1_10
                if (System.Threading.Interlocked.Read(ref H5P_CLS_FILE_CREATE_g) == HID_UNINITIALIZED)
#else
                if (H5P_CLS_OBJECT_CREATE_g == HID_UNINITIALIZED)  //32 bit read is atomic
#endif
                {
                    hid_t val = -1;
                    if (m_importer.GetValue<hid_t>(Constants.DLLFileName,
                        "H5P_CLS_FILE_CREATE_ID_g", ref val,
#if HDF5_VER1_10
                        Marshal.ReadInt64
#else
                        Marshal.ReadInt32
#endif
                        ))
                    {
                        // we could #if ... #else here too but this time it is not needed
                        System.Threading.Interlocked.CompareExchange(ref H5P_CLS_FILE_CREATE_g, val, HID_UNINITIALIZED);
                    }
                }
                return H5P_CLS_FILE_CREATE_g;
            }
        }
```

**Comment by gheber** [comment] 2016-10-17 12:47
Yes, all global identifiers, once initialized, have a positive value. Would there be any harm in doing
```
if (System.Threading.Interlocked.Read(ref H5P_CLS_FILE_CREATE_g) == HID_UNINITIALIZED)
```
? Otherwise the code looks a little mysterious. Even if there were a small performance overhead, it wouldn't be worth the initial "confusion overhead."

**Comment by hokb** [comment] 2016-10-17 12:54
No harm. But I think there is no overload for `Interlocked.Read` which works with `Int32`. Presumably because it is not needed.

**Comment by JanWosnitza** [comment] 2016-10-20 07:57
@`Interlocked.Read` as far as I know reads on architecures native bit-width and below are always atomic. And the Interlocked write operation already takes care of the cache invalidation on all cores.

> [Interlocked.Read](https://msdn.microsoft.com/en-us/library/system.threading.interlocked.read(v=vs.110).aspx):
The Read method is unnecessary on 64-bit systems, because 64-bit read operations are already atomic. On 32-bit systems, 64-bit read operations are not atomic unless performed using Read.

#### Beside that:
I think a better approach would be to initalize the exports within a static constructor. The .Net Runtime takes care of threadsaftyness and maybe it is the fastest method overall, too.

First move all the read global code into a single function:

    internal static class GlobalsHelper
    {
        static GlobalsHelper()
        {
            H5.open();
            m_importer = H5DLLImporter.Create();
        }

        static readonly H5DLLImporter m_importer;

        public static hid_t Read(string globalsName)
        {
            hid_t val = 0;
            m_importer.GetValue<hid_t>(Constants.DLLFileName,
                globalsName, ref val,
    #if HDF5_VER1_10
                            Marshal.ReadInt64
    #else
                            Marshal.ReadInt32
    #endif
                            );
            return val;
        }
    }

and second change the global's defintions to

    public unsafe sealed partial class H5P
    {
        public static hid_t ROOT          { get; } = GlobalsHelper.Read("H5P_CLS_ROOT_ID_g");
        public static hid_t OBJECT_CREATE { get; } = GlobalsHelper.Read("H5P_CLS_OBJECT_CREATE_ID_g");
        public static hid_t FILE_CREATE   { get; } = GlobalsHelper.Read("H5P_CLS_FILE_CREATE_ID_g");
        // ...
    }

The compiler generated code will look like this (ILSpy):
![image](https://cloud.githubusercontent.com/assets/2276629/19550604/8635aaa2-96aa-11e6-99b6-09178bbc3a1b.png)

Don't worry about the `H5.open();` call being at the end, since `H5.open();` is already called within `GlobalsHelper`'s static constructor.

#### Advantages

- No checks when retrieving the value
- Thread-safe for free (also have a look at [Static Constructors](https://msdn.microsoft.com/en-us/library/k9x6w0hc.aspx?f=255&MSPPError=-2147217396) which recommends this method)
- Almost no code duplication, thus the globals generation script might be unneccessary?

#### Disadvantages

- I don't know any. Tell me if you find one :)

**Comment by hokb** [comment] 2016-10-20 17:17
> Disadvantages I don't know any. Tell me if you find one :)
Don't know if this qualifies as such: 
* the main purpose of the current design is to realize lazy initialization. With your approach all 'constants' are initialized at start. Most constants will never be needed though. 
* This is rather a blurred feel and only personal taste: having too many side effects in static constructors can be dangerous. If one of the initialization fails, there will be no second chance. This would render the whole class unusable (and in this case the whole library). 

On the other hand all your 'advantages' hold. For me the code bloat prevention is the biggest one. But we would still use the code generator scripts (nothing wrong with that).

There is a pot. compromize with `Lazy<T>`. This would require switching over to .NET 4.0 though.

**Comment by hokb** [comment] 2016-10-20 17:24
Keep in mind that we are dealing with HDF5 here, involving many accesses to the file system. Preventing from the overhead of things like `Interlocked.Read` would be [premature optimization](http://programmers.stackexchange.com/a/80092/49818) ;)

**Comment by JanWosnitza** [comment] 2016-10-20 18:16
>  - the main purpose of the current design is to realize lazy initialization. With your approach all 'constants' are initialized at start. Most constants will never be needed though.

Indeed, but the initialization is just copying a hand full of integers. The real initialization happens within `H5open();`, and this initializes all globals at once, so why not copy them immediately?

>  - This is rather a blurred feel and only personal taste: having too many side effects in static constructors can be dangerous. If one of the initialization fails, there will be no second chance. This would render the whole class unusable (and in this case the whole library).

As said above: the real side effect happens within `H5open();` which you need to call. I assume the lazy initialization (`if` & `Interlocked`) is more expensive than a simple one time copy.

> Keep in mind that we are dealing with HDF5 here, involving many accesses to the file system. Trying to prevent from the overhead of things like Interlocked.Read would be premature optimization ;)

But then locking would be a perfectly fine solution hehe

**Comment by JanWosnitza** [comment] 2016-10-20 18:29
If you really care about performance, then we should get rid of the properties altogether and use fields instead (which are much faster to access, since no function call is needed):

    public static readonly hid_t ROOT = GlobalsHelper.Read("H5P_CLS_ROOT_ID_g");

**Comment by hokb** [comment] 2016-10-20 19:28
As you know performance is a complex beast. We will never know until we measure something.

**Comment by hokb** [comment] 2016-10-21 06:40
Ah, we [are](https://github.com/HDFGroup/HDF.PInvoke/issues/100) on 4.0 already ;). So we could use Lazy<T> quite easily.

**Comment by hokb** [comment] 2016-10-21 06:45
@janwosnitza 
> So why not copy them immediately?

We could. But we need to acquire the address of each exported constant first. This requires to call into some WINAPI functions ... for each constant individually.

**Comment by JanWosnitza** [comment] 2016-10-21 06:56
I will create a little performance test :)

**Comment by JanWosnitza** [comment] 2016-10-21 07:01
And I agree: if you need only one value and just a couple of times, it would be slower.

Overall I see these use-cases:

- Retrieve a global value a couple of times
  - The current solution would be a little bit faster
  - My solution would be a little bit slower, but you wouldn't notice since it's just a wast of microseconds
- Retrieve a global value a lot
  - The current solution would be little bit slower
  - My solution would be a little bit faster

**Comment by JanWosnitza** [comment] 2016-10-21 08:54
Alright, I've done some tests and (to me unsurprisingly ;-P) they confirmed my theories.

The test is committed on [this branch](https://github.com/JanWosnitza/HDF.PInvoke/tree/globals-speed-test), each commit implementing a different method. And the achieved timings are on this [Google Spread Sheet](https://docs.google.com/spreadsheets/d/1_8In8o7QjWxhz3YfoGrUoAwOVVuXfBp39UT5I7wdopE/edit?usp=sharing). Summarized (all values in seconds):

Method | Access-Time | Init-Time
----------|--------------|---------
Lazy Init (current) | 6.38E-09 | 0.03102
Lazy Init & Interlocked | 20.00E-09 | 0.10469
Static Init & Properties | 4.75E-09 | 0.01587
Static Init & Fields | 4.71E-09 | 0.00834

To me it was unexpected, that even the initialization is faster with the "Static Init". And the "Init-Time"s with "Static Init" shouldn't be different, I think that's just random (pretty hard to get deterministic timings out of .Net ;))

#### Test Setup
I ran the [SpeedTest](https://github.com/JanWosnitza/HDF.PInvoke/blob/globals-speed-test/SpeedTest/Program.cs) twice for every method with different amount of access counts and used the first times I got. "Access-Time" and "Init-Time" were calculated with the formula mentioned above:

    access-time = (total-time-1 - total-time-2) / (access-count-1 - access-count-2)
    init-time = total-time-2 - access-time * access-count-2

**Comment by hokb** [comment] 2016-10-21 10:00
I've quickly tried to reproduce these results but failed. Probably I did something wrong cherrypicking your commits. Is it possible (and easy) to put all these tests into a single commit? this would make it easier for us to reproduce the numbers and improve the tests, if necessary.

**Comment by JanWosnitza** [comment] 2016-10-21 10:15
I used `git --reset hard ID` instead of cherry pick:

Method | Link | Command
----------|-----|------------
Lazy Init (current) | c6029a480a2e3c363f086713bd7eaf82fd84bb1c | `git reset --hard c6029a480a2e3c363f086713bd7eaf82fd84bb1c`
Lazy Init & Interlocked | 40ad5df1491d30fc7828a2a934d3ce90006bf36e | `git reset --hard 40ad5df1491d30fc7828a2a934d3ce90006bf36e`
Static Init & Properties | 3f042a1a7cc59daad24002f6c58f3c844bf08109 | `git reset --hard 3f042a1a7cc59daad24002f6c58f3c844bf08109`
Static Init & Fields | cc4ce1fd454dc848dcfa01845d7a7df87ca7edad | `git reset --hard cc4ce1fd454dc848dcfa01845d7a7df87ca7edad`

But I will try make a different test for each method in a single commit.

**Comment by JanWosnitza** [comment] 2016-10-22 11:28
Oooook, I made a [new Repo](https://github.com/JanWosnitza/NativeDllGlobalsAccessTest) for the "single commit" test.
![image](https://cloud.githubusercontent.com/assets/2276629/19618983/e4697390-985a-11e6-92e9-7868640e9ff8.png)
These numbers look pretty solid.

#### Test Setup
I made a test program, that calls another process which executes the actual tests.
Each method was tested 20 times with 20'000'000 accesses and 20 times with 200'000'000 accesses.
Every test is run in random order.
And the final numbers are calculated from the median times.

**Comment by JanWosnitza** [comment] 2016-10-22 12:09
And some nice [Wolfram graphing](http://www.wolframalpha.com/input/?i=plot+0.00348907777777774%2B4.96476111111111E-09*x,+0.00259152222222214%2B1.19829138888889E-08*x,+0.00452189999999997%2B2.63019E-09*x,+0.00471236666666663%2B2.62414666666667E-09*x+from+x+%3D+80000+to+600000):
![image](https://cloud.githubusercontent.com/assets/2276629/19619183/d1bbe89e-9860-11e6-9393-08ffd3f1dacb.png)
x = access-count
y = total-time
Blue = LazyInit
Purple = LazyInitInterlocked
Yellow = StaticInitProperty
Green = StaticInitField

**Comment by JanWosnitza** [comment] 2016-10-22 14:58
Uuuuh. The Interlocked version doesn't get initialized. That's the reason for it's fast initialization m( Will fix that ;)

**Comment by hokb** [comment] 2016-10-22 16:38
@JanWosnitza thanks for your efforts! I was able to run these tests. I found some flaws (h5open() missing, failed to initialize local fields etc.) Also, your numbers can easily change when varying any of: platform target, HDF5 version with 32bit hids, the set of other processes running on the system during the tests and likely more. But let's try to summarize remaining open questions: 

*Initialize all fields in the static constructor or in a lazy manner*
Static constructor: 
+ +no threading issues. Not during intialize. Not during read. 
-  - all vars are initialized at once, no matter if needed or not.
-  - more complex static class constructor 

Lazy getters: 
+ + only vars really needed are read from the dll. 
- - more code to maintain
- - harder to get threadsafe 

In order to beat me with my own arguments: intializing all ~200 constants at once seems neglectable as well: it costs a couple of milliseconds during startup. Likely in the same range as the JIT would need for the larger code base of lazy, threadsafe getters. So I suggest to switch over to static constructor initialization.

*Properties vers. fields*
Without the lazyness there is little reason to stick to properties and getters at all. It might be a .NET convention to use properties. But I don't really see a reason here. We don't need the extra safety of properties, we don't want to overload them nor do we need fine grained access rules. So, yeah: why not go with fields!?

**Comment by hokb** [comment] 2016-10-22 16:43
@JanWosnitza  oh, and let me know if you want comments on the test setup ;)

**Comment by JanWosnitza** [comment] 2016-10-22 16:49
Alright, I tried to optimize the LazyInitInterlocked version in the meantime ;)
![image](https://cloud.githubusercontent.com/assets/2276629/19620950/cee70014-9887-11e6-9711-e572ff78378a.png)

#### LazyInitInterlocked1 (version from above)
    private static hid_t H5T_IEEE_F32BE_g;

    public static hid_t IEEE_F32BE
    {
        get
        {
            if (System.Threading.Interlocked.Read( ref H5T_IEEE_F32BE_g ) == default( hid_t ))
            {
                hid_t val = m_importer.ReadHid("H5T_IEEE_F32BE_g");
                System.Threading.Interlocked.CompareExchange( ref H5T_IEEE_F32BE_g, val, default( hid_t ) );
            }
            return H5T_IEEE_F32BE_g;
        }
    }

#### LazyInitInterlocked2
    private static int bH5T_IEEE_F32BE_g;
    private static hid_t H5T_IEEE_F32BE_g;

    public static hid_t IEEE_F32BE
    {
        get
        {
            if (bH5T_IEEE_F32BE_g != 0)
                return H5T_IEEE_F32BE_g;

            H5T_IEEE_F32BE_g = m_importer.ReadHid( "H5T_IEEE_F32BE_g" );
            System.Threading.Interlocked.Increment( ref bH5T_IEEE_F32BE_g );
            return H5T_IEEE_F32BE_g;
        }
    }

#### LazyInitInterlocked3
    private static IntPtr H5T_IEEE_F32BE_g;

    public static hid_t IEEE_F32BE
    {
        get
        {
            if (H5T_IEEE_F32BE_g != default( IntPtr ))
                return *(hid_t*) H5T_IEEE_F32BE_g;

            var addr = m_importer.GetAddress("H5T_IEEE_F32BE_g");
            System.Threading.Interlocked.Exchange( ref H5T_IEEE_F32BE_g, addr );
            return *(hid_t*) H5T_IEEE_F32BE_g;
        }
    }

#### StaticInitProperty
    private static readonly hid_t H5T_IEEE_F32BE_g = m_importer.ReadHid( "H5T_IEEE_F32BE_g" );
    public static hid_t IEEE_F32BE => H5T_IEEE_F32BE_g;

**Comment by JanWosnitza** [comment] 2016-10-22 16:51
> @JanWosnitza oh, and let me know if you want comments on the test setup ;)

Sure, go ahead. I know, I completely overdid it, but was kind of fun hehe

**Comment by JanWosnitza** [comment] 2016-10-22 17:05
> I found some flaws (h5open() missing, failed to initialize local fields etc.)

The missing `H5open();` call was on purpose. It just adds a static value to each init-time.
Not sure what you mean with the local fields init. It's .Net, everything is initialized ;)

> Likely in the same range as the JIT would need for the larger code base of lazy, threadsafe getters.

I bet it's more, since a lot of Lazy objects and Delegate objects have to be created first.

#### My summary
I would opt for the static initialization with properties, since it doesn't really change speed and is kind of .Net Standard (as you mentioned).

**Comment by JanWosnitza** [comment] 2016-10-24 12:23
The build is failing, because there are some H5E globals which only exist in 1.10 but not in 1.8.

> But we would still use the code generator scripts (nothing wrong with that).

Personally I count this as a reason against the generator. Making the generator more complicated doesn't sound like a lot of fun.

**Closed** 2017-02-13 07:17 UTC
Labels: enhancement
